version: "3.5"
services:
 # See:
 # https://hub.docker.com/r/bitnami/zookeeper
 zookeeper:
   image: "bitnami/zookeeper:latest"
   container_name: "zookeeper"
   networks:
     - "network-kafka"
   ports:
     - "2181:2181"
   environment:
     ALLOW_ANONYMOUS_LOGIN: "yes"

 # See:
 # https://hub.docker.com/r/bitnami/kafka
 kafka:
   image: bitnami/kafka:latest
   container_name: "kafka"
   networks:
     - "network-kafka"
   ports:
     - "29092:29092"
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     ALLOW_PLAINTEXT_LISTENER: "yes"
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
   depends_on:
     - zookeeper
networks:
 network-kafka:
     name: "network-kafka"