version: '3'

services:

   prometheus:
      container_name: prometheus
      image: prom/prometheus
      volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      command:
      - --config.file=/etc/prometheus/prometheus.yml
      ports:
      - 9090:9090

   grafana:
      container_name: grafana
      image: grafana/grafana
      volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
      ports:
      - 3000:3000
volumes:
   prometheus_data: {}
   grafana_data: {}